version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:latest

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
      - run:
          name: SonarCloud analysis
          command: |
            npm install -g sonar-scanner
            sonar-scanner \
              -Dsonar.projectKey=Eltybear \
              -Dsonar.organization=your_organization_name \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
